folio-org/mod-service-interaction

service/src/main/okapi/tenant/sample_data/widgetDefinitions/erm_agreements_simple_search_widget.json, service/src/main/okapi/tenant/sample_data/widgetTypes/SimpleSearchSchema.json
- updated schema to include valueType on result columns
=> Iteration 2

service/src/main/okapi/tenant/sample_data/widgetDefinitions/erm_agreements_simple_search_widget.json, service/src/main/okapi/tenant/sample_data/widgetDefinitions/erm_licenses_simple_search_widget.json, service/src/main/okapi/tenant/sample_data/widgetTypes/SimpleSearchSchema.json
Tweaks to the schema and example ERM agreements definition
Added ERM Licenses definition
=> ERM-1562: Customise simple search widget instance

NEWS.md, service/src/main/okapi/tenant/sample_data/widgetDefinitions/erm_agreements_simple_search_widget.json, service/src/main/okapi/tenant/sample_data/widgetDefinitions/erm_licenses_simple_search_widget.json, service/src/main/okapi/tenant/sample_data/widgetTypes/SimpleSearchSchema.json
=> ERM-1579: Add parameter / token support for simple search

service/grails-app/controllers/org/olf/DashboardController.groovy, service/grails-app/controllers/org/olf/WidgetInstanceController.groovy
=> Changes to isOwner logic on Dashboard/WidgetInstance Controller

service/src/main/okapi/tenant/sample_data/_data.groovy
Bootstrapping now uses inputStream
=> Change to bootstrapped code

service/build.gradle
=> use https for maven repos

service/grails-app/conf/logback.groovy, service/src/main/okapi/tenant/sample_data/_data.groovy
Fixed bootstrapping code, added temporary extra logging for backend OkapiClient and HttpBuilder
=> ERM-1643 fix to bootstrapping code

service/build.gradle, service/grails-app/conf/application-vagrant-db.yml, service/grails-app/conf/application.yml, service/grails-app/conf/logback.groovy, service/grails-app/services/org/olf/WidgetDefinitionService.groovy
Pulled in new version of grails-okapi : 4.1.1
Changes to discard data of wrong shape (with warning) rather than try to assimilate it
Changes to okapi development config to help warn about these issues in future
=> ERM-1643 fixes

service/build.gradle, service/grails-app/controllers/org/olf/NumberGeneratorController.groovy, service/grails-app/controllers/org/olf/UrlMappings.groovy, service/grails-app/domain/org/olf/numgen/NumberGenerator.groovy, service/grails-app/domain/org/olf/numgen/NumberGeneratorSequence.groovy, service/grails-app/migrations/module-tenant-changelog.groovy, service/grails-app/migrations/number-generator-model.groovy, service/grails-app/views/numberGenerator/_numberGenerator.gson, service/grails-app/views/numberGeneratorSequence/_numberGeneratorSequence.gson, service/src/integration-test/groovy/org/olf/BaseSpec.groovy, service/src/integration-test/groovy/org/olf/SILifecycleSpec.groovy, service/src/main/okapi/ModuleDescriptor-template.json, tools/testing/docker-compose.yml, tools/testing/init.sql
Feat: Add number generator backend, integration testing
=> Number generator

service/grails-app/views/numberGeneratorSequence/_numberGeneratorSequence.gson
Expand checkDigitAlgo on the view for a NumberGeneratorSequence
=> feat: CheckDigitAlgo

service/grails-app/controllers/org/olf/DashboardController.groovy, service/grails-app/controllers/org/olf/UrlMappings.groovy, service/src/main/okapi/ModuleDescriptor-template.json
Added endpoint to dashboard to check "my access" level
refs ERM-2312, ERM-2313
=> feat: Access endpoint

service/grails-app/services/org/olf/DashboardService.groovy
Fixed place where we were looking for access.dashboard instead of existingAccess.dashboard
ERM-2312
=> fix: Access null safety

service/grails-app/domain/org/olf/Dashboard.groovy, service/grails-app/migrations/service-interaction-1-3.groovy
Added a description field to Dashboard
ERM-2314
=> feat: Dashboard Description

service/grails-app/domain/org/olf/numgen/NumberGeneratorSequence.groovy, service/grails-app/migrations/number-generator-model.groovy, service/grails-app/services/org/olf/HousekeepingService.groovy
Added name column to number generator sequence.
=> feat: Sequence name

scripts/okapi-login, scripts/register_and_enable_rancher.sh, scripts/run_rancher_desktop.sh, scripts/secure_enable.sh, scripts/secure_register.sh, service/grails-app/conf/application-rancher-desktop-db.yml
Changes to allow module to run using rancher-desktop
=> feat: Rancher desktop

scripts/run_rancher_desktop.sh, scripts/secure_enable.sh, scripts/secure_register.sh, service/grails-app/conf/application-rancher-desktop-db.yml
=> fix: rancher-desktop

NEWS.md, service/gradle.properties
Release 2.0.0, NEWS.md updated and SNAPSHOT removed from build version
ERM-2238
=> chore: Release 2.0.0

NEWS.md, service/gradle.properties
NEWS.md update and removed SNAPSHOT from version
=> chore: Release 2.1.0

service/grails-app/controllers/org/olf/NumberGeneratorController.groovy, service/src/integration-test/groovy/org/olf/SILifecycleSpec.groovy
Ensure sequence name in initialiseDefaultSequence, also fixed integration test
=> fix: initialise default sequence

NEWS.md, service/gradle.properties
Added details to NEWS.md and rmoeved SNAPSHOT from version #
ERM-2494
=> chore: Release 2.2.0

service/grails-app/services/org/olf/HousekeepingService.groovy
Added generators for accession number, call number and item barcode, reformatted JSON for other sequences too
=> feat: Inventory generators

service/build.gradle
chore: KIWT
Bumped KIWT to rc4
=> Bumped KIWT version to release candidate 4 for custprop filtering

NEWS.md, service/build.gradle
* update web-toolkit to version 8.1.0
* edit NEWS.md
=> ERM-2966 Error when match and filter contain the same path root

service/build.gradle, service/grails-app/services/org/olf/HousekeepingService.groovy
Added generator for publication pattern number within serials management
[UISER-34](https://issues.folio.org/browse/UISER-34)
=> feat: Serials management generator

service/grails-app/domain/org/olf/Dashboard.groovy, service/grails-app/migrations/module-tenant-changelog.groovy, service/grails-app/migrations/service-interaction-3-0.groovy
feat: Dashboard display data
Added a String field to house generic display data about the dashboard. Have not explicitly modelled as this is display only data and we should not particularly care
refs ERM-2971, ERM-1795
=> ERM-2971: Back end changes to support storing location/dimensions of widgets

service/grails-app/services/org/olf/HousekeepingService.groovy
Fixed serials management generator to have code values be correct length
=> fix: Serials management generator

.gitignore, NEWS.md, service/gradle.properties
=> ERM-2652: mod-service-interaction release. Fix version: 3.0.0 (Poppy)

service/grails-app/controllers/org/olf/UrlMappings.groovy, service/grails-app/controllers/org/olf/numberGenerator/NumberGeneratorController.groovy, service/grails-app/controllers/org/olf/numberGenerator/NumberGeneratorSequenceController.groovy, service/src/main/okapi/ModuleDescriptor-template.json
Endpoints to allow direct GET/POST/PUT/DELETE of number generator sequences, in readiness for a better settings page
=> SI-4: Add search, sort and filter to Sequences page

service/build.gradle
build: Update version of 'com.github.everit-org.json-schema:org.everit.json.schema' (#99)
Updated version of 'com.github.everit-org.json-schema:org.everit.json.schema' to 1.14.3 to avoid DoS and OOM issue
refs ERM-3112, ERM-3116
=> Release 3.0.2

NEWS.md
=> docs: Added patch releases to master branch of NEWS.md

service/grails-app/views/numberGenerator/_numberGenerator.gson, service/grails-app/views/numberGeneratorSequence/_numberGeneratorSequence.gson
When controller is not numberGeneraorController, expand a snippet of the owner on the sequence
refs SI-22
=> feat: Expand owner on sequences

service/grails-app/controllers/org/olf/numberGenerator/NumberGeneratorController.groovy, service/grails-app/domain/org/olf/numgen/NumberGeneratorSequence.groovy, service/grails-app/migrations/number-generator-model.groovy, service/grails-app/services/org/olf/HousekeepingService.groovy, service/src/integration-test/groovy/org/olf/SILifecycleSpec.groovy, tools/testing/docker-compose.yml
Enable numgen to apply a template before checksum calculation.
=> Feat: pre checksum template values

GUIDANCE.md, LICENSE, service/build.gradle
docs: Update module license, guidance and dependencies
SI-71
=> SI-71: Update module license, guidance and dependencies for mod-service-interaction

service/grails-app/controllers/org/olf/numberGenerator/NumberGeneratorController.groovy, service/grails-app/services/org/olf/HousekeepingService.groovy
chore: Rename checksum labels
Also ensure default sequences are initialised with non-null outputTemplates
SI-76
=> More NumGen tweaks for Ramsons

NEWS.md
Added news section reflected in 4.1.1 release
=> chore: Post-release 4.1.1

service/src/main/okapi/ModuleDescriptor-template.json
Added okapi interface to module descriptor
SI-96
=> chore: Added missing interfaces from module descriptor

NEWS.md, service/gradle.properties, service/src/main/okapi/ModuleDescriptor-template.json
Added NEWS.md section and bumped version to 4.1.2
SI-97
=> Release 4.1.2

NEWS.md, service/gradle.properties
Bumped version to 4.2.0 and added NEWS.md section
SI-77
=> chore: Release 4.2.0

NEWS.md, service/gradle.properties
Added NEWS.md section, bumped app version to 4.3.0-SNAPSHOT and okapi interface to 4.3
SI-77
=> chore: Post release 4.2.0

NEWS.md
Added NEWS.md section reflected in release 4.2.1
=> chore: Post release 4.2.1

service/build.gradle
Bumped kafka-clients and jackson dependencies
SI-121
=> SI-121: kafka-clients 3.7.2, jackson 2.18.3 fixing vulns

service/build.gradle
Bumped undertow version to 2.2.37
SI-120
=> SI-120: Upgrade undertow from 2.2.28.Final to 2.2.37.Final fixing vulns

NEWS.md
Added NEWS.md section reflected in 4.2.2 release
=> docs: Post release 4.2.2
